version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.16

commands:
  install_terraform:
    description: install terraform in go container
    steps:
      - run:
          name: Create Terraform Credentials file
          command: echo "credentials \"app.terraform.io\" { token = \"$TF_CLOUD_TOKEN\" }" >$HOME/.terraformrc
      - run:
          name: Install Terraform
          environment:
            TF_VERSION: 1.0.1
          command: |
            mkdir -p ~/bin
            cd ~/bin
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip
            echo 'export PATH=~/bin:$PATH'  >> $BASH_ENV
            terraform --version
  run_init:
    description: run terratest init
    steps:
      - run:
          name: Run terraform init
          command: |
            terraform --version
            cd prod/
            terraform init

jobs:
  run-terraform-init:
    executor: golang
    steps:
      - checkout
      - install_terraform
      - run_init

workflows:
  version: 2
  on-commit:
    jobs:
      - run-terraform-init
